apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: weather
      tlsSkipVerify: true
    secureJsonData:
      token: CHANGE_ME_TO_SECURE_TOKEN
    editable: true
